### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by kazuyakusastro** [malikolivier/aflak#4]
kazuya@dospara2015:~/data/vis-ifu/aflak$ aflak
Traceback (most recent call last):
  File "/usr/bin/aflak", line 5, in <module>
    from aflak.aflak import main
  File "/data/kazuya/vis-ifu/aflak/aflak/aflak.py", line 6, in <module>
    import aflak.mainwindow
  File "/data/kazuya/vis-ifu/aflak/aflak/mainwindow.py", line 3, in <module>
    from .mainwindow_ui import Ui_MainWindow
  File "/data/kazuya/vis-ifu/aflak/aflak/mainwindow_ui.py", line 109, in <module>
    from .AstroImageView import AstroImageView
  File "/data/kazuya/vis-ifu/aflak/aflak/AstroImageView.py", line 13, in <module>
    from .WCSAxis import WCSAxes
  File "/data/kazuya/vis-ifu/aflak/aflak/WCSAxis.py", line 7, in <module>
    from .fits import FITSUnit
  File "/data/kazuya/vis-ifu/aflak/aflak/fits.py", line 8, in <module>
    class FITSUnit(enum.Enum):
  File "/data/kazuya/vis-ifu/aflak/aflak/fits.py", line 9, in FITSUnit
    DEGREE = enum.auto()
AttributeError: module 'enum' has no attribute 'auto'

**Comment by malikolivier** [comment]
Python version: 3.5.3

**Comment by malikolivier** [comment]
I reproduced the bug.

`enum.auto` is a new feature from Python 3.6. Current `Debian Stretch` ships with Python 3.5.3.

https://docs.python.org/3/library/enum.html#enum.auto
